apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: de7fkmd8b-nodejs 
  janus-idp.io/tekton: de7fkmd8b-nodejs
  backstage.io/kubernetes-id: de7fkmd8b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: de7fkmd8b-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml